# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.waveCombo = QtWidgets.QComboBox(Widget)
        self.waveCombo.setObjectName("waveCombo")
        self.waveCombo.addItem("")
        self.waveCombo.addItem("")
        self.waveCombo.addItem("")
        self.waveCombo.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.waveCombo)
        self.positionSpin = QtWidgets.QDoubleSpinBox(Widget)
        self.positionSpin.setObjectName("positionSpin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.positionSpin)
        self.goPosBut = QtWidgets.QPushButton(Widget)
        self.goPosBut.setObjectName("goPosBut")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.goPosBut)
        self.goWaveBut = QtWidgets.QPushButton(Widget)
        self.goWaveBut.setObjectName("goWaveBut")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.goWaveBut)
        self.label = QtWidgets.QLabel(Widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.positionLbl = QtWidgets.QLabel(Widget)
        self.positionLbl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.positionLbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.positionLbl.setObjectName("positionLbl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.positionLbl)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.insertButton = QtWidgets.QPushButton(Widget)
        self.insertButton.setObjectName("insertButton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.insertButton)
        self.lineEdit = QtWidgets.QLineEdit(Widget)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setMinimumWidth(600)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.textBrowser = QtWidgets.QTextBrowser(Widget)
        self.textBrowser.setObjectName("textBrowser")

        self.textBrowser.setTextBackgroundColor(QtGui.QColor(5,5,5))
        self.textBrowser.setTextColor(QtGui.QColor(0, 255, 0))
        self.textBrowser.setStyleSheet("background-color: black;")
        self.textBrowser.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignBottom)
        self.textBrowser.insertPlainText("0gi\n")
        self.textBrowser.insertPlainText("0PO12931223\n")

        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.waveCombo.setItemText(0, _translate("Widget", "510 nm"))
        self.waveCombo.setItemText(1, _translate("Widget", "405 nm"))
        self.waveCombo.setItemText(2, _translate("Widget", "365 nm"))
        self.waveCombo.setItemText(3, _translate("Widget", "280 nm"))
        self.goPosBut.setText(_translate("Widget", "Go!"))
        self.goWaveBut.setText(_translate("Widget", "Go!"))
        self.label.setText(_translate("Widget", "Location:"))
        self.positionLbl.setText(_translate("Widget", "0.00 mm"))
        self.insertButton.setText(_translate("Widget", "Insert"))
