# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(487, 381)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")

        if False:
            self.verticalLayout = QtWidgets.QVBoxLayout()
            self.verticalLayout.setObjectName("verticalLayout")
            self.label = QtWidgets.QLabel(Form)
            self.label.setObjectName("label")
            self.verticalLayout.addWidget(self.label)
            self.monitorBox = QtWidgets.QCheckBox(Form)
            self.monitorBox.setObjectName("monitorBox")
            self.verticalLayout.addWidget(self.monitorBox)
            self.receiverBox = QtWidgets.QCheckBox(Form)
            self.receiverBox.setObjectName("receiverBox")
            self.verticalLayout.addWidget(self.receiverBox)
            self.ratioBox = QtWidgets.QCheckBox(Form)
            self.ratioBox.setObjectName("ratioBox")
            self.verticalLayout.addWidget(self.ratioBox)
            self.comboBox = QtWidgets.QComboBox(Form)
            self.comboBox.setObjectName("comboBox")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.setMaximumWidth(200)
            self.verticalLayout.addWidget(self.comboBox)
            self.label_2 = QtWidgets.QLabel(Form)
            self.label_2.setObjectName("label_2")
            self.verticalLayout.addWidget(self.label_2)
            self.showFitBox = QtWidgets.QCheckBox(Form)
            self.showFitBox.setObjectName("showFitBox")
            self.verticalLayout.addWidget(self.showFitBox)
            self.rollingBox = QtWidgets.QCheckBox(Form)
            self.rollingBox.setObjectName("rollingBox")
            self.verticalLayout.addWidget(self.rollingBox)
            self.spinBox = QtWidgets.QSpinBox(Form)
            self.spinBox.setMinimum(1)
            self.spinBox.setObjectName("spinBox")
            self.spinBox.setMaximumWidth(200)
            self.verticalLayout.addWidget(self.spinBox)

            self.pvalLayout = QtWidgets.QHBoxLayout()
            self.pvalLayout.setObjectName("pvalLayout")
            self.pval_lbl = QtWidgets.QLabel()
            self.pval_lbl.setText("Fit p-value: ")
            self.pval_lbl.setObjectName("pbal_lbl")
            self.pval_lbl.setMaximumWidth(50)
            self.pvalLayout.addWidget(self.pval_lbl)
            self.pval_value = QtWidgets.QLabel()
            self.pval_value.setText("nan")
            self.pval_value.setObjectName("pval_value")
            self.pval_value.setMaximumWidth(50)
            self.pvalLayout.addWidget(self.pval_value)
            self.pvalLayout.setAlignment(QtCore.Qt.AlignLeft)
            self.pvalLayout.setSizeConstraint(150)
            self.verticalLayout.addLayout(self.pvalLayout)

            self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
            self.horizontalLayout_2.setObjectName("horizontalLayout_2")
            self.horizontalLayout_2.setSizeConstraint(150)
            self.horizontalLayout_2.setAlignment( QtCore.Qt.AlignLeft)
            self.mintime = QtWidgets.QDoubleSpinBox(Form)
            self.mintime.setMaximum(10000.0)
            self.mintime.setSingleStep(0.5)
            self.mintime.setObjectName("mintime")
            self.mintime.setMaximumWidth(200)
            self.mintime.setSizePolicy(QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Minimum)
            self.horizontalLayout_2.addWidget(self.mintime)
            self.timelbl = QtWidgets.QLabel(Form)
            self.timelbl.setObjectName("timelbl")
            self.timelbl.setMaximumWidth(50)
            self.timelbl.setSizePolicy(QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Minimum)
            self.horizontalLayout_2.addWidget(self.timelbl)
            self.maxtime = QtWidgets.QDoubleSpinBox(Form)
            self.maxtime.setMaximumWidth(200)
            self.maxtime.setMaximum(10000.0)
            self.maxtime.setValue(10000)
            self.maxtime.setSingleStep(0.5)
            self.maxtime.setObjectName("maxtime")
            self.maxtime.setSizePolicy(QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Minimum)
            self.horizontalLayout_2.addWidget(self.maxtime)
            self.verticalLayout.addLayout(self.horizontalLayout_2)


            spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
            self.verticalLayout.addItem(spacerItem)


            self.horizontalLayout.addLayout(self.verticalLayout)
        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        self.toolbar = NavigationToolbar(self.canvas, Form)
        self.toolbar.setSizePolicy(QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Minimum)
        self.canvas.setSizePolicy(QtWidgets.QSizePolicy.Expanding,QtWidgets.QSizePolicy.Expanding)
        self.zoombut = QtWidgets.QCheckBox(Form)
        self.zoombut.setObjectName("zoombut")
        self.zoombut.setText("Auto Zoom")
        self.zoombut.setChecked(True)
        #self.verticalLayout.addWidget(self.toolbar)

        self.new_vert = QtWidgets.QVBoxLayout()
        self.new_vert.setObjectName("new_vert")

        self.new_vert.addWidget(self.canvas)
        self.new_vert.addWidget(self.toolbar)
        self.new_vert.addWidget(self.zoombut)
        self.horizontalLayout.addLayout(self.new_vert)
        



        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate

        Form.setWindowTitle(_translate("Form", "Form"))
        if False:
            self.label.setText(_translate("Form", "Show:"))
            self.monitorBox.setText(_translate("Form", "Monitor"))
            self.receiverBox.setText(_translate("Form", "Receiver"))
            self.ratioBox.setText(_translate("Form", "Ratio"))
            self.comboBox.setItemText(0, _translate("Form", "Mu"))
            self.comboBox.setItemText(1, _translate("Form", "No-Pulse Rate"))
            self.comboBox.setItemText(2, _translate("Form", "Pulse Rate"))
            self.comboBox.setItemText(3, _translate("Form", "Charge Dist."))
            self.label_2.setText(_translate("Form", "Options:"))
            self.showFitBox.setText(_translate("Form", "Show Fit"))
            self.rollingBox.setText(_translate("Form", "Rolling?"))
            self.timelbl.setText(_translate("Form", "time range"))
