# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HVWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 287)

        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")


        self.name_lbl = QtWidgets.QLabel(Widget)
        self.name_lbl.setObjectName("name_lbl")
        self.verticalLayout_3.addWidget(self.name_lbl)

        self.on_button = QtWidgets.QPushButton(Widget)
        self.on_button.setObjectName("on_button")
        self.on_button.setText("Turn ON")
        self.verticalLayout_3.addWidget(self.on_button)

        self.off_button = QtWidgets.QPushButton(Widget)
        self.off_button.setObjectName("off_button")
        self.off_button.setText("Turn Off")
        self.verticalLayout_3.addWidget(self.off_button)

        self.on_box = QtWidgets.QCheckBox(Widget)
        self.on_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.on_box.setObjectName("on_box")
        self.on_box.setEnabled(False)
        self.verticalLayout_3.addWidget(self.on_box)

        self.rdwn_box = QtWidgets.QCheckBox(Widget)
        self.rdwn_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rdwn_box.setObjectName("rdwn_box")
        self.rdwn_box.setEnabled(False)
        self.verticalLayout_3.addWidget(self.rdwn_box)

        self.rup_box = QtWidgets.QCheckBox(Widget)
        self.rup_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rup_box.setObjectName("rup_box")
        self.rup_box.setEnabled(False)
        self.verticalLayout_3.addWidget(self.rup_box)

        self.ovv_box = QtWidgets.QCheckBox(Widget)
        self.ovv_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ovv_box.setObjectName("ovv_box")
        self.ovv_box.setEnabled(False)
        self.verticalLayout_3.addWidget(self.ovv_box)
        
        self.ovc_box = QtWidgets.QCheckBox(Widget)
        self.ovc_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ovc_box.setObjectName("ovc_box")
        self.ovc_box.setEnabled(False)
        self.verticalLayout_3.addWidget(self.ovc_box)

        self.unv_box = QtWidgets.QCheckBox(Widget)
        self.unv_box.setObjectName("unv_box")
        self.unv_box.setEnabled(False)
        self.verticalLayout_4.addWidget(self.unv_box)
        
        self.maxv_box = QtWidgets.QCheckBox(Widget)
        self.maxv_box.setObjectName("maxv_box")
        self.maxv_box.setEnabled(False)
        self.verticalLayout_4.addWidget(self.maxv_box)

        self.trip_box = QtWidgets.QCheckBox(Widget)
        self.trip_box.setObjectName("trip_box")
        self.trip_box.setText("TRIP")
        self.trip_box.setEnabled(False)
        self.verticalLayout_4.addWidget(self.trip_box)

        self.OVP_box = QtWidgets.QCheckBox(Widget)
        self.OVP_box.setObjectName("OVP_box")
        self.OVP_box.setText("OVP")
        self.OVP_box.setEnabled(False)
        self.verticalLayout_4.addWidget(self.OVP_box)

        self.RES0_box = QtWidgets.QCheckBox(Widget)
        self.RES0_box.setObjectName("RES0_box")
        self.RES0_box.setText("RES0")
        self.RES0_box.setEnabled(False)
        self.verticalLayout_4.addWidget(self.RES0_box)

        self.DIS_box = QtWidgets.QCheckBox(Widget)
        self.DIS_box.setObjectName("DIS_box")
        self.DIS_box.setText("DIS")
        self.DIS_box.setEnabled(False)
        self.verticalLayout_4.addWidget(self.DIS_box)

        self.KILL_box = QtWidgets.QCheckBox(Widget)
        self.KILL_box.setObjectName("KILL_box")
        self.KILL_box.setText("KILL")
        self.KILL_box.setEnabled(False)
        self.verticalLayout_4.addWidget(self.KILL_box)

        self.ILK_box = QtWidgets.QCheckBox(Widget)
        self.ILK_box.setObjectName("ILK_box")
        self.ILK_box.setText("ILK")
        self.ILK_box.setEnabled(False)
        self.verticalLayout_4.addWidget(self.ILK_box)

        self.NOCAL_box = QtWidgets.QCheckBox(Widget)
        self.NOCAL_box.setObjectName("NOCAL_box")
        self.NOCAL_box.setText("NOCAL")
        self.NOCAL_box.setEnabled(False)
        self.verticalLayout_3.addWidget(self.NOCAL_box)

        self.RES1_box = QtWidgets.QCheckBox(Widget)
        self.RES1_box.setObjectName("RES1_box")
        self.RES1_box.setText("RES1")
        self.RES1_box.setEnabled(False)
        self.verticalLayout_3.addWidget(self.RES1_box)

        self.RES2_box = QtWidgets.QCheckBox(Widget)
        self.RES2_box.setObjectName("RES2_box")
        self.RES2_box.setText("RES2")
        self.RES2_box.setEnabled(False)
        self.verticalLayout_3.addWidget(self.RES2_box)



        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.voltage_set = QtWidgets.QDoubleSpinBox(Widget)
        self.voltage_set.setMaximum(9000)
        self.voltage_set.setMinimum(1)
        self.voltage_set.setObjectName("voltage_set")
        self.gridLayout.addWidget(self.voltage_set, 0, 1, 1, 1)
        self.apply_v = QtWidgets.QPushButton(Widget)
        self.apply_v.setObjectName("apply_v")
        self.gridLayout.addWidget(self.apply_v, 0, 3, 1, 1)
        self.vset_lbl = QtWidgets.QLabel(Widget)
        self.vset_lbl.setObjectName("vset_lbl")
        self.gridLayout.addWidget(self.vset_lbl, 0, 0, 1, 1)
        self.voltage_disp = QtWidgets.QLabel(Widget)
        self.voltage_disp.setObjectName("voltage_disp")
        self.gridLayout.addWidget(self.voltage_disp, 0, 2, 1, 1)
        self.iset_lbl = QtWidgets.QLabel(Widget)
        self.iset_lbl.setObjectName("iset_lbl")
        self.gridLayout.addWidget(self.iset_lbl, 1, 0, 1, 1)
        self.current_set = QtWidgets.QDoubleSpinBox(Widget)
        self.current_set.setObjectName("current_set")
        self.current_set.setMaximum(9000)
        self.current_set.setMinimum(0)
        self.gridLayout.addWidget(self.current_set, 1, 1, 1, 1)
        self.current_disp = QtWidgets.QLabel(Widget)
        self.current_disp.setObjectName("current_disp")
        self.gridLayout.addWidget(self.current_disp, 1, 2, 1, 1)
        self.apply_I = QtWidgets.QPushButton(Widget)
        self.apply_I.setObjectName("apply_I")
        self.gridLayout.addWidget(self.apply_I, 1, 3, 1, 1)

        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.on_box.setText(_translate("Widget", "ON"))
        self.rdwn_box.setText(_translate("Widget", "RAMP DOWN"))
        self.rup_box.setText(_translate("Widget", "RAMP UP"))
        self.ovv_box.setText(_translate("Widget", "Over Voltage"))
        self.ovc_box.setText(_translate("Widget", "Over Current"))
        self.unv_box.setText(_translate("Widget", "Under Voltage"))
        self.maxv_box.setText(_translate("Widget", "Max Voltage"))
        self.apply_v.setText(_translate("Widget", "Apply"))
        self.vset_lbl.setText(_translate("Widget", "Voltage Setting"))
        self.voltage_disp.setText(_translate("Widget", "------"))
        self.iset_lbl.setText(_translate("Widget", "Current Setting"))
        self.current_disp.setText(_translate("Widget", "------"))
        self.apply_I.setText(_translate("Widget", "Apply"))
